### ISSUE TITLE
Curious

### ISSUE THREAD

**Issue by JimSEOW** [sergey-tihon/OpenNLP.NET#2]
There is no Chinese Model for OpenNLP. 
Do you think it is possible for us to port the Chinese Model from StanfordNLP.NET to OpenNLP ?

**Comment by sergey-tihon** [comment]
Closed this as an old issues.
Anyway I think that answer is No. 
It is not clear what model, but the only way is to find public training set, transform it to something consumable by Open NLP trainer and train new model
