### ISSUE TITLE
Unable to convert model .bin to .nbin, vice versa

### ISSUE THREAD

**Issue by vineet-singh26** [sergey-tihon/OpenNLP.NET#20]
Hi folks,
I need some help/ guidance in converting models from [https://opennlp.sourceforge.net/models-1.5/](url) to .nbin format. 
I am stuck with this. I tried model convertor shared [https://www.codeproject.com/articles/12109/statistical-parsing-of-english-sentences?display=print&fid=229482&df=90&mpp=25&sort=Position&view=Normal&spc=Relaxed&fr=101&prof=True](url) but **I didn't find any success.**

Please, any help here is really appreciative. Thankyou !!

Error: **Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection JavaBinaryGisModelReader**

**Comment by sergey-tihon** [comment]
What is `.nbin` and why you decided to convert?

If you use this project ([OpenNLP.NET](https://github.com/sergey-tihon/OpenNLP.NET)) is perfectly fine to use original models without any conversion. You can check the code samples in tests https://github.com/sergey-tihon/OpenNLP.NET/blob/master/tests/OpenNLP.NET.Tests/Tests.cs#L117-L128

**Comment by vineet-singh26** [comment]
I was looking for a POSTagging model when I came across your project. Hats off to the work you've done here. But the project is dependent on IKVM which we can't introduce into our codebase because of security reasons. I'd have loved to use your project but unfortunately I had to look for alternatives and I came across [``](https://github.com/AlexPoint/OpenNlp)

**Comment by sergey-tihon** [comment]
I see that you already created issues in another repo https://github.com/AlexPoint/OpenNlp/issues/36

Sorry, I know nothing about `.nbin` format.

Close this issue because it is not related to this repo.

**Comment by sergey-tihon** [comment]
You can take a look at models here https://github.com/AlexPoint/OpenNlp/tree/master/Resources/Models

Then maybe check out repo, try to compile, and take a look at the trainers code. Somewhere in the repo should be code that create `*.nbin` files

**Comment by sergey-tihon** [comment]
> But the project is dependent on IKVM which we can't introduce into our codebase because of security reasons.

Do you know any security vulnerabilities of IKVM? Just wonder what they are about.

**Comment by vineet-singh26** [comment]
Hi @sergey-tihon ,
Thanks for quick reply!!

We get this remark from our security team.
"IKVM is a java virtual machine implemented in .NET.  Outside of the license risk that seems like a pretty broad attack surface."

we are looking for an MIT based solution. I admired you work with stanford.nlp, but that too used GPL license with IKVM. That's the issue. Thanks !!!

**Comment by wasabii** [comment]
The license risk concern is pretty unfounded, unless there's a general concern with all Java, as all JVMs are under the same license at this point. And is silly if you're using, say, Linux, since the OpenJDK license is more FOSS than Linux itself.

It being a JVM and a JVM being big is a legitimate concern I suppose. More of "the unknown."
