### ISSUE TITLE
Strong Naming Support

### ISSUE THREAD

**Issue by NightOwl888** [sergey-tihon/OpenNLP.NET#6]
Due to the fact the assembly is not strong named/strong signed, there are some supportability problems, namely we are having issues because of lack of [InternalsVisibleTo](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=net-5.0) support with our strong-named assemblies.

Someone has already cloned this project and [released a strong-named copy on NuGet.org](https://www.nuget.org/packages/OpenNLP.NET.Signed/), but I would prefer to depend on packages maintained by original authors.

Ideally, we would like to still use 1.9.1 (perhaps versioned 1.9.1.1 to show it is patched), but we could probably adapt to using 1.9.2 or the latest version, 1.9.3 if you would rather upgrade at the same time.

**Comment by sergey-tihon** [comment]
Sure, no problem at all. 
I've released version [1.9.1.1](https://www.nuget.org/packages/OpenNLP.NET/1.9.1.1) with signed assemblies

**Comment by NightOwl888** [comment]
Thanks for the quick turn-around. All looks good.
